name: greenhouse_client
description: Mobile MQTT client for the ESP32 smart greenhouse.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.6.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
